// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "censys_alert_system/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// AlertStorageInterface is an autogenerated mock type for the AlertStorageInterface type
type AlertStorageInterface struct {
	mock.Mock
}

// CreateAlert provides a mock function with given fields: ctx, source, severity, description, wholeEvent, enrichmentType, ipAddress, createdAt
func (_m *AlertStorageInterface) CreateAlert(ctx context.Context, source string, severity string, description string, wholeEvent []byte, enrichmentType string, ipAddress string, createdAt time.Time) error {
	ret := _m.Called(ctx, source, severity, description, wholeEvent, enrichmentType, ipAddress, createdAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []byte, string, string, time.Time) error); ok {
		r0 = rf(ctx, source, severity, description, wholeEvent, enrichmentType, ipAddress, createdAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAlertByID provides a mock function with given fields: ctx, id
func (_m *AlertStorageInterface) GetAlertByID(ctx context.Context, id string) (*models.Alert, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAlertByID")
	}

	var r0 *models.Alert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Alert, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Alert); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Alert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAlerts provides a mock function with given fields: ctx
func (_m *AlertStorageInterface) GetAlerts(ctx context.Context) ([]models.Alert, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAlerts")
	}

	var r0 []models.Alert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Alert, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Alert); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Alert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAlertsByDays provides a mock function with given fields: ctx, days
func (_m *AlertStorageInterface) GetAlertsByDays(ctx context.Context, days int) ([]models.Alert, error) {
	ret := _m.Called(ctx, days)

	if len(ret) == 0 {
		panic("no return value specified for GetAlertsByDays")
	}

	var r0 []models.Alert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.Alert, error)); ok {
		return rf(ctx, days)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.Alert); ok {
		r0 = rf(ctx, days)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Alert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, days)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastSyncTime provides a mock function with given fields: ctx
func (_m *AlertStorageInterface) GetLastSyncTime(ctx context.Context) (time.Time, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLastSyncTime")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (time.Time, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) time.Time); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLastSyncTime provides a mock function with given fields: ctx, t
func (_m *AlertStorageInterface) UpdateLastSyncTime(ctx context.Context, t time.Time) error {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastSyncTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAlertStorageInterface creates a new instance of AlertStorageInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlertStorageInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlertStorageInterface {
	mock := &AlertStorageInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
