// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	external "censys_alert_system/external"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// APIClientInterface is an autogenerated mock type for the APIClientInterface type
type APIClientInterface struct {
	mock.Mock
}

// CheckHealth provides a mock function with given fields: ctx
func (_m *APIClientInterface) CheckHealth(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckHealth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchAlertsSince provides a mock function with given fields: ctx, since
func (_m *APIClientInterface) FetchAlertsSince(ctx context.Context, since time.Time) ([]external.ExternalAlert, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for FetchAlertsSince")
	}

	var r0 []external.ExternalAlert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]external.ExternalAlert, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []external.ExternalAlert); ok {
		r0 = rf(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]external.ExternalAlert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchAllAlerts provides a mock function with given fields: ctx
func (_m *APIClientInterface) FetchAllAlerts(ctx context.Context) ([]external.ExternalAlert, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchAllAlerts")
	}

	var r0 []external.ExternalAlert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]external.ExternalAlert, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []external.ExternalAlert); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]external.ExternalAlert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAPIClientInterface creates a new instance of APIClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPIClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *APIClientInterface {
	mock := &APIClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
